services:
  # 1. Uptime Kuma（host 网络，无法端口绑定）
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always
    network_mode: "host"
    environment:
      - PORT=${UPTIME_KUMA_PORT}
    volumes:
      - ./data/uptime-kuma:/app/data
    # 说明：
    # host 模式下端口监听由程序决定
    # 建议后续通过防火墙限制 12861 仅 Tailscale 访问

  # 2. FileCodeBox
  filecodebox:
    image: lanol/filecodebox:latest
    container_name: filecodebox
    restart: always
    volumes:
      - ./data/filecodebox:/app/data
    ports:
      - "${TAILSCALE_IP}:${FILECODEBOX_PORT}:12345"

  # 3. Excalidraw
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: always
    ports:
      - "${TAILSCALE_IP}:${EXCALIDRAW_PORT}:80"

  # 4. Sun-Panel（唯一全监听入口）
  sun-panel:
    image: "hslr/sun-panel:latest"
    container_name: sun-panel
    restart: always
    ports:
      - "${SUN_PANEL_PORT}:3002"
    volumes:
      - ./data/sun-panel/conf:/app/conf
      - ./data/sun-panel/uploads:/app/uploads
      - ./data/sun-panel/database:/app/database
      - /var/run/docker.sock:/var/run/docker.sock

  # 5. Kula
  kula:
    image: c0m4r/kula:latest
    container_name: kula
    restart: always
    pid: host
    network_mode: "host"
    volumes:
      - /proc:/proc:ro
      - ./data/kula:/app/data
    environment:
      - KULA_PORT=${KULA_PORT}

  # 6. SyncTV
  synctv:
    image: synctvorg/synctv:latest
    container_name: synctv
    restart: always
    ports:
      - "${TAILSCALE_IP}:${SYNCTV_PORT}:8080"
    volumes:
      - ./data/synctv:/app/data

  # # 7. Alist
  # alist:
  #   image: 'xhofe/alist:latest'
  #   container_name: alist
  #   restart: always
  #   volumes:
  #     - './data/alist:/opt/alist/data'
  #   ports:
  #     - "${TAILSCALE_IP}:5244:5244"
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - UMASK=022

  # 7. webdav同步配置
  webdav:
    image: bytemark/webdav
    container_name: webdav
    restart: always
    environment:
      - AUTH_TYPE=${WEBDAV_AUTH_TYPE}
      - USERNAME=${WEBDAV_USERNAME}
      - PASSWORD=${WEBDAV_PASSWORD}
    ports:
      - "${WEBDAV_PORT}:80"
    volumes:
      - ./data/webdav:/var/lib/dav
